### ISSUE TITLE
[BUG]: Minor updates and UI changes

### ISSUE THREAD

**Issue by adapap** [Idleon-Companion/IdleonCompanion#86]
## Cards/Assets
- [x] Fix reverse scrolling with right click
- [x] Add tip to left/right click
  - [x] Extract to game asset wrapper component?
- [x] Check in-game layout to match new W3 data
- [x] Images should not be draggable (also confirm click regions)

**Comment by F1r3w477** [comment]
I think if you add the option to hover an icon to see the name and possibly boosts/costs, you should allow people to "unlock" each bubble in the tracker. Otherwise, people might get spoilers for different bubbles, and some people might not appreciate that.

**Comment by adapap** [comment]
Sure, we can add a default/missing image for non-unlocked bubbles!
